package tyche

const (
	ERROR_CONSUMER_GROUP_NAME   = "error-reader-group"
	FAILED_CONSUMER_GROUP_NAME  = "failed-reader-group"
	PENDING_CONSUMER_GROUP_NAME = "pending-reader-group"
	SENT_CONSUMER_GROUP_NAME    = "sent-reader-group"
	SUCCEED_CONSUMER_GROUP_NAME = "succeed-reader-group"
)

const (
	DEFAULT_CONSUMER_NAME = "consumer-name"
	ERROR_CONSUMER_NAME   = DEFAULT_CONSUMER_NAME
	FAILED_CONSUMER_NAME  = DEFAULT_CONSUMER_NAME
	PENDING_CONSUMER_NAME = DEFAULT_CONSUMER_NAME
	SENT_CONSUMER_NAME    = DEFAULT_CONSUMER_NAME
	SUCCEED_CONSUMER_NAME = DEFAULT_CONSUMER_NAME
)
